openapi: 3.0.0
info:
  description: |
    Тестовое задание для потока Backend Xsolla School 2021. API позволяет управлять товарами с помощью методов CRUD.
  version: "1.0.0"
  title: Products
  contact:
    email: workmaximov@yandex.ru
tags:
  - name: product
    description: Информация о товаре
paths:
  /api/products:
    get:
      tags:
        - product
      summary: Получить каталог товаров
      operationId: getProducts
      parameters: 
        - name: offset
          in: query
          description: Отступ, с которым берутся записи из БД
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '304':
          description: Достигнут конец каталога товаров
    post:
      tags:
        - product
      summary: Создать товар
      operationId: postProducts
      responses:
        '200':
          description: успех
          content:
            application/json:
              schema:
                type: string
                example: 'game-FarCry-3fa85f64-5717-4562-b3fc-2c963f66afa6'
  '/api/products{id}':
    get:
      tags:
        - product
      summary: Получить продукт по идентификатору или SKU
      operationId: getProduct
      parameters:
        - name: id
          in: path
          description: Идентификатор или SKU товара
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успех
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Product'
    delete:
      tags:
        - product
      summary: Удалить товар
      operationId: deleteProduct
      parameters:
        - name: id
          in: path
          description: Идентификатор или SKU товара
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успех
    put:
      tags:
        - product
      summary: Изменить товар
      operationId: updateProduct
      parameters:
        - name: id
          in: path
          description: Идентификатор или SKU товара
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успех
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: '3fa85f64-5717-4562-b3fc-2c963f66afa6'
        name:
          type: string
          example: FarCry
        type:
          type: string
          example: game
        price:
          type: string
          example: '9001'
        sku:
          type: string
          example: 'game-FarCry-3fa85f64-5717-4562-b3fc-2c963f66afa6'
  requestBodies:
    Product:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Product'
      description: Объект товара
    ProductsArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Product'
      description: Каталог товаров
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/VladislavMaksimov/xsolla-school-2021-backend/1.0.0